name: CastleWars
main: fr.ezzud.castlewar.Main
version: 1.0.3
author: Ezzud
softdepend: 
   - NametagEdit
commands:
  castlewar:
    description: Main command
    aliases: ["cw", "war", "castle"]
    default: true